### ISSUE TITLE
Missing Person

### ISSUE THREAD

**Issue by ArjanSeijs** [Goldiriath/Quests#14]
* [ ] script quest
  - [ ] create quest file
  - [ ] create dialogue
* [ ] create mob spawns
* [ ] Texture for bear
* [ ] Texture for bear prints and footprints (optional)

Simple Level 1 Quest

This quest can be obtained by talking to the mother of the missing person or when asking about the local news in a tavern, or if you stumble on the bear cave in the world.

The mother is standing at the edge of town when you approach her she calls to you:

### Stage 0
**Mother:**
  "Hey, you there adventurer! You look like you can handle yourself, I need your help!"
### Stage 1
> 1 Ask whats wrong
> 2 [Ignore]

1:
**Mother:**
  "I need someone to look from my son, he went missing in the forest a few days ago when he was gathering wood."
2:
**Mother:**
  "Please come back if you change your mind"
### Stage 2
> 1 Ask for reward
> 2 Accept
> 3 Decline

1)
 "I don't have much but I will make sure to make it worth your while.
  Will cut back to Stage 2 dialogue
2) 
  "Thank you!" [Description of location last seen]
3)
 Ends Quest

### Stage 3
When you approach the described location
**Narrator**
  "As you approach [location description] you see a axe on the ground, it looks like someone left in a hurry. You see foot prints and animal tracks"

> 1 Investigate animal tracks
> 2 Follow the tracks

1)**Narrator**
  "As you inspect the footprints and animal tracks it is clear that someone was running from the animal. It looks like they was chased by a bear"

Go the stage 4

### Stage 4
When you approach the bear cave
**Narrator**
  "The tracks lead into the cave, there is a faint smell of fish"

The player sees a bear here and a npc up an ledge.

> 1 Attack Bear
> 2 Distract bear with fish (if fish in inventory)
> 3 Leave

When the bear is dead go to stage 5

### Stage 5
**Son**
"Thank you for saving me"

### Stage 6
Going back to the mother for reward and end quest.

**Comment by JeromSar** [comment]
Nice intro quest, me likey!
Q: How are you going to give the player the option of using the fish?
Q: How are we going to teleport the son after he's been saved? One solution: use two copies of the NPC and make either one invisible.
Q: How are we going to let the bear be distracted by fish? (Custom AI?)

**Comment by cashenkes** [comment]
maybe a bear is not a good level 1 enemy but it could be a weak or wounded bear. Rest of the quest looks solid. 

A little idea is to add another path with the fish, that you could have the fish poisoned if you talk to the <hunter> after figuring out that it is a bear you're dealing with. And then after giving the bear the fish it dies.

Another option (that does work with the previous one) is to have the bear be sleeping at first. If the player is sneakily he can take the child and leave without the bear waking up. Can still choose to fight the bear and can use the fish to kill the bear.

Also might be a nice touch to have the NPC follow the player back till town unless the player runs away or something then the NPC can teleport back and the mother will be slightly angry with the player.
